const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'dist/*',
      // Vendored gluestack registry — regenerated by `gluestack-ui add`.
      'components/ui/**',
      // Generated from @radix-ui/colors by scripts/generate-radix-ramps.mjs.
      'theme/radix-ramps.ts',
    ],
  },
  {
    // Screens and app-level components must go through gluestack + tokens.
    files: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'react-native',
              importNames: [
                'Alert',
                'TouchableOpacity',
                'ActivityIndicator',
                'StyleSheet',
              ],
              message:
                'Use gluestack instead: Alert -> useConfirm/useAppToast, TouchableOpacity -> Button/Pressable, ActivityIndicator -> Spinner, StyleSheet -> className. See AGENTS.md.',
            },
            {
              name: '@react-native-community/slider',
              message: 'Use @/components/ui/slider.',
            },
          ],
          patterns: [
            {
              group: ['@/constants/theme'],
              message:
                'Colors is a legacy shim. Use className tokens, or useToken() from @/theme/use-token.',
            },
          ],
        },
      ],
    },
  },
  {
    // Tests and dev scripts legitimately reach for raw RN primitives.
    files: [
      '**/*.test.{ts,tsx}',
      'test-utils/**/*.{ts,tsx}',
      'scripts/**/*.{js,mjs}',
    ],
    rules: {
      'no-restricted-imports': 'off',
      // The generator indexes @radix-ui/colors by computed hue name.
      'import/namespace': 'off',
    },
  },
  {
    /*
     * CardContent renders a WebView whose height is measured at runtime and
     * fed back through postMessage. react-native-webview takes a real style
     * object, not a className, so StyleSheet is correct here — this is the
     * only place in the app where that is true.
     */
    files: ['components/CardContent.tsx'],
    rules: { 'no-restricted-imports': 'off' },
  },
]);
